from typing import Any
from sqlalchemy import String, JSON
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class FlashcardSet(Base):
    """Persisted flashcard set generated by the Groq AI."""

    __tablename__ = "flashcard_sets"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    topic: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="The topic of the flashcards requested by the user",
    )

    cards: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON,
        nullable=False,
        comment="JSON array of generated flashcards (front/back)",
    )

    model_used: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="llama-3.1-8b-instant",
        comment="Groq model identifier used for generation",
    )
