from typing import Any
from sqlalchemy import String, JSON
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class StudyPlan(Base):
    """Persisted study plan generated by the Groq AI."""

    __tablename__ = "study_plans"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    subjects: Mapped[list[str]] = mapped_column(
        JSON,
        nullable=False,
        comment="The subjects to be studied as requested by the user",
    )
    
    exam_date: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        comment="The target exam date",
    )

    plan: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON,
        nullable=False,
        comment="JSON array of daily plans",
    )

    model_used: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="llama-3.1-8b-instant",
        comment="Groq model identifier used for generation",
    )
