from sqlalchemy import String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class NoteSummary(Base):
    """Persisted notes summary generated by the Groq AI."""

    __tablename__ = "note_summaries"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)

    original_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The raw notes text provided by the user",
    )

    summary_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The summarized text returned by the AI",
    )

    model_used: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="llama-3.1-8b-instant",
        comment="Groq model identifier used for generation",
    )
