"""Add study_plans table

Revision ID: f68b78d502e1
Revises: 919e72a65ce4
Create Date: 2026-07-28 15:51:21.031220
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'f68b78d502e1'
down_revision: Union[str, None] = '919e72a65ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False, comment='The subjects to be studied as requested by the user'),
    sa.Column('exam_date', sa.String(length=20), nullable=False, comment='The target exam date'),
    sa.Column('plan', sa.JSON(), nullable=False, comment='JSON array of daily plans'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Groq model identifier used for generation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_id'), 'study_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plans_id'), table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
