"""Add flashcards table

Revision ID: 919e72a65ce4
Revises: 2ef7405ad6ec
Create Date: 2026-07-28 15:42:12.322497
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '919e72a65ce4'
down_revision: Union[str, None] = '2ef7405ad6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False, comment='The topic of the flashcards requested by the user'),
    sa.Column('cards', sa.JSON(), nullable=False, comment='JSON array of generated flashcards (front/back)'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Groq model identifier used for generation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_sets_id'), 'flashcard_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcard_sets_id'), table_name='flashcard_sets')
    op.drop_table('flashcard_sets')
    # ### end Alembic commands ###
