"""Add note summaries table

Revision ID: 28324bd02541
Revises: 947ac3df62a9
Create Date: 2026-07-28 15:07:16.044841
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = '28324bd02541'
down_revision: Union[str, None] = '947ac3df62a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False, comment='The raw notes text provided by the user'),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='The summarized text returned by the AI'),
    sa.Column('model_used', sa.String(length=100), nullable=False, comment='Groq model identifier used for generation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_summaries_id'), 'note_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_summaries_id'), table_name='note_summaries')
    op.drop_table('note_summaries')
    # ### end Alembic commands ###
